version: '3'
services:
    briefthreat:
        image: briefthreat/app
        build: .
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./app.env
    db:
        image: mariadb:latest
        restart: always
        env_file:
            - ./common.env
            - ./mysql.env
        volumes:
            - $MYSQL_DATA:/var/lib/mysql
    nginx:
        image: briefthreat/nginx
        build:
            context: .
            dockerfile: Dockerfile.nginx
        depends_on:
            - briefthreat
        env_file:
            - ./nginx.env
        ports:
            - "80:80"
