FROM nginx:mainline-alpine

RUN mkdir /opt/briefthreat
COPY nginx.conf /opt/briefthreat.conf.template
CMD envsubst '${NGINX_HOST}' < /opt/briefthreat.conf.template > /etc/nginx/conf.d/briefthreat.conf && exec nginx -g 'daemon off;'
