version: '3'
services:
    briefthreat:
        image: briefthreat/app
        build: ./build
        depends_on:
            - db
        env_file:
            - ./common.env
            - ./app.env
        volumes:
            - ./app:/opt/app:ro
    db:
        image: mariadb:latest
        restart: always
        env_file:
            - ./common.env
            - ./mysql.env
        volumes:
            - $MYSQL_DATA:/var/lib/mysql
    nginx:
        image: briefthreat/nginx
        build:
            context: ./build
            dockerfile: Dockerfile.nginx
        depends_on:
            - briefthreat
        env_file:
            - ./nginx.env
        ports:
            - "80:80"
